ARG RHEL_MAJOR=9
FROM registry.access.redhat.com/ubi${RHEL_MAJOR}:latest

ARG RHEL_MAJOR=9
ARG LOCALE=en_US.UTF-8
ARG ENGINE=icu
ARG EXPECTED_MD5
ARG PG_MAJOR=15

ENV TEST_LOCALE=${LOCALE}
ENV TEST_ENGINE=${ENGINE}
ENV EXPECTED_MD5=${EXPECTED_MD5}
ENV LANG=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8

RUN if [ "${RHEL_MAJOR}" = 7 ]; then \
      yum install -y ca-certificates gzip \
      && yum install -y "https://download.postgresql.org/pub/repos/yum/reporpms/EL-${RHEL_MAJOR}-x86_64/pgdg-redhat-repo-latest.noarch.rpm" \
      && sed -i 's/rhel-7Server/rhel-7.10/g' /etc/yum.repos.d/pgdg-redhat-all.repo \
      && sed -i 's/^repo_gpgcheck[[:space:]]*=.*/repo_gpgcheck=0/g' /etc/yum.repos.d/pgdg-redhat-all.repo \
      && yum --disablerepo='pgdg12*' --disablerepo='pgdg13*' --disablerepo='pgdg15*' install -y postgresql${PG_MAJOR}-server postgresql${PG_MAJOR} \
      && yum clean all; \
    else \
      dnf install -y ca-certificates glibc-langpack-en gzip \
      && dnf install -y "https://download.postgresql.org/pub/repos/yum/reporpms/EL-${RHEL_MAJOR}-x86_64/pgdg-redhat-repo-latest.noarch.rpm" \
      && dnf install -y postgresql${PG_MAJOR}-server postgresql${PG_MAJOR} \
      && dnf clean all \
      && rm -rf /var/cache/dnf; \
    fi

COPY --chmod=644 unicode-sorting.sql unicode-sorting-md5.sql /opt/unicode-sorting/
WORKDIR /opt/unicode-sorting

RUN mkdir -p /var/lib/pgsql/data \
    && chown -R postgres:postgres /var/lib/pgsql /opt/unicode-sorting \
    && chmod -R a+rX /opt/unicode-sorting \
    && su postgres -c "/usr/pgsql-${PG_MAJOR}/bin/initdb -D /var/lib/pgsql/data --encoding=UTF8 --locale=en_US.UTF-8"

CMD set -eu; \
    test_started="$(date +%s)"; \
    libc_version="$(rpm -q --qf '%{VERSION}-%{RELEASE}.%{ARCH}' glibc)"; \
    pg_version="$(rpm -q --qf '%{VERSION}-%{RELEASE}.%{ARCH}' postgresql${PG_MAJOR}-server)"; \
    su postgres -c "/usr/pgsql-${PG_MAJOR}/bin/pg_ctl -D /var/lib/pgsql/data -l /tmp/postgresql.log start"; \
    curl -ks "https://www.unicode.org/Public/15.0.0/ucd/UnicodeData.txt" | cut -d';' -f1-3 > /opt/unicode-sorting/UnicodeData.txt; \
    chmod 644 /opt/unicode-sorting/UnicodeData.txt; \
    if [ "${TEST_ENGINE}" = icu ]; then \
      su postgres -c "/usr/pgsql-${PG_MAJOR}/bin/psql -v ON_ERROR_STOP=1 -c \"CREATE COLLATION \\\"${TEST_LOCALE}\\\" (provider = icu, locale = '${TEST_LOCALE}');\"" || true; \
    else \
      su postgres -c "/usr/pgsql-${PG_MAJOR}/bin/psql -v ON_ERROR_STOP=1 -c \"CREATE COLLATION \\\"${TEST_LOCALE}\\\" (locale = '${TEST_LOCALE}');\"" || true; \
    fi; \
    su postgres -c "/usr/pgsql-${PG_MAJOR}/bin/psql -v ON_ERROR_STOP=1 -v UNICODE_VERS=15 -v UNICODE_FILE=/opt/unicode-sorting/UnicodeData.txt -c \"SET work_mem = '256MB';\" -f /opt/unicode-sorting/unicode-sorting.sql"; \
    sed "s/@LOCALE@/\\\"${TEST_LOCALE}\\\"/g" /opt/unicode-sorting/unicode-sorting-md5.sql > /tmp/unicode-sorting-md5.sql; \
    su postgres -c "/usr/pgsql-${PG_MAJOR}/bin/psql -At -v ON_ERROR_STOP=1 -f /tmp/unicode-sorting-md5.sql" | tee /tmp/unicode-sorting-md5-output; \
    result="$(sed -n 's/^[0-9a-f][0-9a-f]*$/&/p' /tmp/unicode-sorting-md5-output | tail -1)"; \
    echo "locale=${TEST_LOCALE} md5=${result} expected=${EXPECTED_MD5}"; \
    echo "libc_version=${libc_version} postgresql_version=${pg_version} test_runtime_seconds=$(( $(date +%s) - test_started ))"; \
    if [ -n "${EXPECTED_MD5}" ]; then \
      test "${result}" = "${EXPECTED_MD5}"; \
    else \
      echo 'No expected MD5 supplied; checksum was not compared'; \
      exit 2; \
    fi
